//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_test_videos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_videos_testEntities : DbContext
    {
        public db_videos_testEntities()
            : base("name=db_videos_testEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<fact_estado> fact_estado { get; set; }
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_estatus_material> fact_estatus_material { get; set; }
        public virtual DbSet<fact_estatus_qa> fact_estatus_qa { get; set; }
        public virtual DbSet<fact_generos> fact_generos { get; set; }
        public virtual DbSet<fact_municipio> fact_municipio { get; set; }
        public virtual DbSet<fact_tipo_usuarios> fact_tipo_usuarios { get; set; }
        public virtual DbSet<inf_centro> inf_centro { get; set; }
        public virtual DbSet<inf_contacto> inf_contacto { get; set; }
        public virtual DbSet<inf_fecha_transformacion> inf_fecha_transformacion { get; set; }
        public virtual DbSet<inf_material> inf_material { get; set; }
        public virtual DbSet<inf_subcentros> inf_subcentros { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
    }
}
