//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_transcriptEntities : DbContext
    {
        public db_transcriptEntities()
            : base("name=db_transcriptEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<inf_fecha_transformacion> inf_fecha_transformacion { get; set; }
        public virtual DbSet<fact_aspx> fact_aspx { get; set; }
        public virtual DbSet<fact_estado> fact_estado { get; set; }
        public virtual DbSet<fact_estatus> fact_estatus { get; set; }
        public virtual DbSet<fact_estatus_material> fact_estatus_material { get; set; }
        public virtual DbSet<fact_estatus_qa> fact_estatus_qa { get; set; }
        public virtual DbSet<fact_estatus_sesion> fact_estatus_sesion { get; set; }
        public virtual DbSet<fact_generos> fact_generos { get; set; }
        public virtual DbSet<fact_municipio> fact_municipio { get; set; }
        public virtual DbSet<fact_tipo_rfc> fact_tipo_rfc { get; set; }
        public virtual DbSet<fact_tipo_usuarios> fact_tipo_usuarios { get; set; }
        public virtual DbSet<inf_caducidad_videos> inf_caducidad_videos { get; set; }
        public virtual DbSet<inf_centro> inf_centro { get; set; }
        public virtual DbSet<inf_credenciales> inf_credenciales { get; set; }
        public virtual DbSet<inf_empresa> inf_empresa { get; set; }
        public virtual DbSet<inf_log_videos> inf_log_videos { get; set; }
        public virtual DbSet<inf_material> inf_material { get; set; }
        public virtual DbSet<inf_ruta_videos> inf_ruta_videos { get; set; }
        public virtual DbSet<inf_sesion> inf_sesion { get; set; }
        public virtual DbSet<inf_subcentros> inf_subcentros { get; set; }
        public virtual DbSet<inf_usuarios> inf_usuarios { get; set; }
    }
}
