//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_caducidad_videos
    {
        public int id_caducidad_videos { get; set; }
        public Nullable<int> dias_caducidad { get; set; }
        public System.Guid id_usuario { get; set; }
        public System.Guid id_centro { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
    
        public virtual inf_centro inf_centro { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
