//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_test_videos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_material
    {
        public int id_material { get; set; }
        public string expediente { get; set; }
        public string sesion { get; set; }
        public string archivo { get; set; }
        public Nullable<int> bits { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_estatus_material { get; set; }
        public Nullable<int> id_estatus_qa { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_estatus_material fact_estatus_material { get; set; }
        public virtual fact_estatus_qa fact_estatus_qa { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
