//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_sesion
    {
        public int id_sesion { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> id_estatus_sesion { get; set; }
        public Nullable<int> id_aspx { get; set; }
        public System.Guid id_usuario { get; set; }
    
        public virtual fact_aspx fact_aspx { get; set; }
        public virtual fact_estatus_sesion fact_estatus_sesion { get; set; }
        public virtual inf_usuarios inf_usuarios { get; set; }
    }
}
