//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_test_videos
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_centro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_centro()
        {
            this.inf_fecha_transformacion = new HashSet<inf_fecha_transformacion>();
            this.inf_subcentros = new HashSet<inf_subcentros>();
        }
    
        public System.Guid id_centro { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public string colonia { get; set; }
        public string calle_num { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string telefono_alt { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
    
        public virtual fact_municipio fact_municipio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_fecha_transformacion> inf_fecha_transformacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_subcentros> inf_subcentros { get; set; }
    }
}
