//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_usuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inf_usuarios()
        {
            this.inf_caducidad_videos = new HashSet<inf_caducidad_videos>();
            this.inf_credenciales = new HashSet<inf_credenciales>();
            this.inf_fecha_transformacion = new HashSet<inf_fecha_transformacion>();
            this.inf_log_videos = new HashSet<inf_log_videos>();
            this.inf_material = new HashSet<inf_material>();
            this.inf_ruta_videos = new HashSet<inf_ruta_videos>();
            this.inf_sesion = new HashSet<inf_sesion>();
        }
    
        public System.Guid id_usuario { get; set; }
        public string codigo_usuario { get; set; }
        public string nombres { get; set; }
        public string a_paterno { get; set; }
        public string a_materno { get; set; }
        public string clave { get; set; }
        public Nullable<int> id_genero { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<int> id_tipo_usuario { get; set; }
        public Nullable<System.DateTime> fecha_nacimiento { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.Guid> id_centro { get; set; }
    
        public virtual fact_estatus fact_estatus { get; set; }
        public virtual fact_generos fact_generos { get; set; }
        public virtual fact_tipo_usuarios fact_tipo_usuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_caducidad_videos> inf_caducidad_videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_credenciales> inf_credenciales { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_fecha_transformacion> inf_fecha_transformacion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_log_videos> inf_log_videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_material> inf_material { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_ruta_videos> inf_ruta_videos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<inf_sesion> inf_sesion { get; set; }
    }
}
