//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wa_transcript
{
    using System;
    using System.Collections.Generic;
    
    public partial class inf_subcentros
    {
        public System.Guid id_subcentro { get; set; }
        public Nullable<int> id_estatus { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public string nombre { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public string colonia { get; set; }
        public string calle_num { get; set; }
        public string cp { get; set; }
        public string telefono { get; set; }
        public string telefono_alt { get; set; }
        public string email { get; set; }
        public string email_alt { get; set; }
        public System.Guid id_centro { get; set; }
    
        public virtual inf_centro inf_centro { get; set; }
    }
}
